### ISSUE TITLE
discussion board

### ISSUE THREAD

**Issue by ingo-m** [wviechtb/scrum-club#1]
I was wondering whether there is going to be some sort of discussion board? Perhaps a gitter channel? (And I would like to apologise in advance for being a few minutes late for today’s meeting because of an experiment.)

**Comment by wviechtb** [comment]
YES! We set up a Slack channel: https://scrum-club.slack.com/ We use it at the moment mostly for the organization, planning, and logistics. Feel free to join!

**Comment by stijnimaging** [comment]
The Slack channel could work, but goes only by invitation of the workspace administrator. Consider to automatically accept all Maastricht University domains. Personally I also prefer Gitter.

**Comment by wviechtb** [comment]
We are trying out Gitter right now. Go here: https://gitter.im/scrum-club/

**Comment by wviechtb** [comment]
Closing this as it seems that we have decided to switch over to Gitter.
